BARCODE_HISTORY : '1'
BARCODE_STATUS : '2'
BARCODE_RESET : 'r'
BARCODE_CLEAR : 'c'
WEAPON_DATA_PATH : 'data/weapon_data.csv'
PERSON_DATA_PATH : 'data/person_data.csv'
HISTORY_DATA_PATH : 'data/data_history.csv'
UNIT_NAME : 'ร้อย.๓ พัน.๒ รร.จปร.'
LOGO_PATH : 'data/crma_logo.png' #'data/thaiarmy_logo.png'